#!/usr/bin/python

Import('env')

vb = env.Clone()
vb.Depends('../../../source/blender/makesrna/intern/RNA_blender_cpp.h', 'makesrna')

sources = vb.Glob('*/*.c') + vb.Glob('*/*.cpp') + vb.Glob('*/*/*.c') + vb.Glob('*/*/*.cpp')  + vb.Glob('*/*/*/*.cpp')

includes = [
    '../../../intern/guardedalloc',
    '../../../intern/smoke/extern',
    '../../../intern/smoke/extern',
    '../blenkernel',
    '../blenlib',
    '../blenloader',
    '../makesdna',
    '../makesrna',
    '../makesrna/intern',
    '../render/extern/include',
    '../render/intern/include',
    '../windowmanager',
    '../python',
    '../python/intern',
    './python',
    './utils',
    './vrscene_exporter',
    './vrscene_exporter/plugins',
    './vrscene_exporter/nodes',
    './',
]

includes.extend(env['BF_PYTHON_INC'].split())
includes.append(env['BF_BOOST_INC'])
includes.append(env['BF_ZLIB_INC'])

if env['OURPLATFORM'] in {'win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc'}:
    includes.append(env['BF_PTHREADS_INC'])

vb.BlenderLib(
    libname  = 'vray_for_blender',
    sources  = sources,
    includes = includes,
    defines  = [],
    libtype  = ['core'],
    priority = [600]
)
