#!/usr/bin/python

Import('env')

sources = env.Glob('*/*.c') + env.Glob('*/*.cpp') + env.Glob('*/*/*.c') + env.Glob('*/*/*.cpp')

includes = [
    '../../../intern/guardedalloc',
    '../../../intern/smoke/extern',
    '../../../intern/smoke/extern',
    '../blenkernel',
    '../blenlib',
    '../blenloader',
    '../makesdna',
    '../makesrna',
    '../makesrna/intern',
    '../render/extern/include',
    '../render/intern/include',
    '../windowmanager',
    '../python',
    '../python/intern',
    './python',
    './utils',
    './vrscene_exporter',
    './vrscene_exporter/plugins',
    './vrscene_exporter/nodes',
    './',
]

includes.extend(env['BF_PYTHON_INC'].split())
includes.append(env['BF_BOOST_INC'])
includes.append(env['BF_ZLIB_INC'])

if env['OURPLATFORM'] in {'win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc'}:
    includes.append(env['BF_PTHREADS_INC'])

env.BlenderLib(
    libname  = 'vray_for_blender',
    sources  = sources,
    includes = includes,
    defines  = [],
    libtype  = ['core'],
    priority = [600]
)
